### ISSUE TITLE
new feature: help add proxy

### ISSUE THREAD

**Issue by Tianqi-Dotes** [Russell-Newton/TikTokPy#11]
hi, due to region limitations, some ppl have to visit tiktok with a network proxy,
could you help add proxy while navigating tiktok
thanx

**Comment by Russell-Newton** [comment]
Implemented in v0.1.8 by specifying launch options in kwargs of [TikTokAPI](https://tiktokpy.readthedocs.io/en/stable/generated/reference/tiktokapipy.api.TikTokAPI.html) or the AsyncTikTokAPI.

Full details of the launch options can be found in [Playwright's Documentation](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch).

Example for using a proxy:

```py
from tiktokapiypy.api import TikTokAPI

with TikTokAPI(proxy={
  "server": "http://myproxy.com:3128",
  "username": "usr",
  "password": "pwd"
}) as api:
    ...
```

**Comment by Russell-Newton** [comment]
Related to #29 - Proxy setup should be working now as of `0.1.11`.

**Comment by zakrian07** [comment]
hey this is not working waiting until "load"
