### ISSUE TITLE
Get Video URL

### ISSUE THREAD

**Issue by brodycritchlow** [Russell-Newton/TikTokPy#12]
Is there a way to get the video url from the Video object

**Comment by Russell-Newton** [comment]
See the function [video_link](https://tiktokpy.readthedocs.io/en/stable/generated/reference/tiktokapipy.models.video.video_link.html#tiktokapipy.models.video.video_link) in models.video:

```py
from tiktokapipy.models.video import video_link

link = video_link(some_video_obj.id)
```
