### ISSUE TITLE
Comments no loading on both chromium and firefox

### ISSUE THREAD

**Issue by icrni** [Russell-Newton/TikTokPy#23]
It seems comments are not loading again, for both firefox and chromium navigator types.
Only confirmed locally on windows wsl environment if it makes any difference.

**Comment by Russell-Newton** [comment]
Sorry for the late response, what other initialization parameters were you using? Do you have a snippet of your code?

**Comment by icrni** [comment]
Hi, sorry, just got back to this again. Tested again with latest version and same error. I tried both Chrome and Firefox
```
from tiktokapipy.api import TikTokAPI
from tiktokapipy.models import video as video_model

with TikTokAPI(navigator_type="chrome", scroll_down_time=1, data_dump_file="test.json") as api:
    user = api.user("khaby.lame")
    for video in user.videos:
        video_url = video_model.video_link(video.id)
        print(video.comments)
```

**Comment by Russell-Newton** [comment]
Please try again in version 0.1.13. This should be resolved.

**Comment by Russell-Newton** [comment]
I'm closing this issue as completed in 0.1.13. If for some reason it hasn't been resolved for you, either reopen this issue or create a new one. Happy scraping!
