### ISSUE TITLE
how to get the basic video info LightVideo from user.videos and avoid query other time consuming data

### ISSUE THREAD

**Issue by Tianqi-Dotes** [Russell-Newton/TikTokPy#25]
hi,
how can I get the basic video info `LightVideo` from user.videos and avoid query data in `Video`.
I found comment data easy to throw exceptions and time-consuming.
![image](https://user-images.githubusercontent.com/36755957/214579220-56fbca08-c201-45a6-b934-c3f025a605ce.png)
Maybe I can firstly get the basic video id set of a user and decide what I want next steps. Then query other video details by the video id I have got.

**Comment by Russell-Newton** [comment]
At the moment, the best option is to use `user.videos._light_models`. This is hidden from the documentation, but I'll make a better solution when I can in the next couple of days

**Comment by Russell-Newton** [comment]
Additionally, the comment ValidationError issue has been addressed in v0.1.10.post2
