### ISSUE TITLE
Suppressing certain warnings and errors

### ISSUE THREAD

**Issue by pjn5047** [Russell-Newton/TikTokPy#26]
Is there an easy way to suppress some of the warnings related to the comments not loading? I am not trying to collect any comments, so suppressing these would make things easier. 

For instance, when I get the following when I start using the API:
```
site-packages/tiktokapipy/api.py:470: UserWarning: Was unable to collect comments.
A second attempt might work.
  warnings.warn(
```

Additionally, I get the following for some videos:
```
  File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 19 validation errors for APIResponse
comments -> 0 -> id
  field required (type=value_error.missing)
comments -> 1 -> id
  field required (type=value_error.missing)
comments -> 2 -> id
  field required (type=value_error.missing)
```

Any suggestions would be appreciated! Sorry if this is obvious to others.

**Comment by Russell-Newton** [comment]
When you run your python program, you can use `-Wignore` to suppress warnings. Also, I fixed the issue that caused the ValidationErrors due to comments in `v0.1.10.post2`.
