### ISSUE TITLE
Is there a way to ignore slideshows or Error in video extraction: status code 100004?

### ISSUE THREAD

**Issue by pjn5047** [Russell-Newton/TikTokPy#27]
I believe I'm getting and error because I'm trying to extract data from a slideshow. I know I could utilize `emulate_mobile=True`, however this severely limits the number of videos I am able to pull data on. Traceback on the error is below:

```
Traceback (most recent call last):
  File "~/myproject.py", line 52, in <module>
    for video in challenge.videos:
  File "~/venv/lib/python3.10/site-packages/tiktokapipy/api.py", line 90, in __next__
    out = self.fetch(self._next_up)
  File "~/venv/lib/python3.10/site-packages/tiktokapipy/api.py", line 103, in fetch
    return self._api.video(video_link(self._light_models[idx].id))
  File "~/venv/lib/python3.10/site-packages/tiktokapipy/api.py", line 312, in video
    return self._extract_video_from_response(response, api_extras)
  File "~/venv/lib/python3.10/site-packages/tiktokapipy/api.py", line 450, in _extract_video_from_response
    raise TikTokAPIError(
tiktokapipy.TikTokAPIError: Error in video extraction: status code 100004
```

I can't seem to figure out where to put my `except:` statement since even calling the video in the `for videos in challenge.videos` causes the error, so I'm not sure how to move to the next iteration.

Any help is appreciated! Again, I apologize if there is a simple solution I am just missing.

**Comment by pjn5047** [comment]
I ended up instead pulling the "light" video information from challenge.videos._light_models, then iterating over that ids in that list with a try/except so that I could skip over the errors and continue to the next video. It's probably inefficient, but it works for now!

**Comment by Russell-Newton** [comment]
Just a heads up, I updated the code such that the `videos._light_models` is now `videos.light_models`. Also, this is kind of the best way to do it at the moment. There currently isn't a more efficient way to do it, you just have to step through the iterator yourself

**Comment by Russell-Newton** [comment]
Just a heads up, I updated the code such that the `videos._light_models` is now `videos.light_models`. Also, this is kind of the best way to do it at the moment. There currently isn't a more efficient way to do it, you just have to step through the iterator yourself

**Comment by Russell-Newton** [comment]
Small update - it looks like slideshows now work on desktop too, so you may not see this problem anymore.
