### ISSUE TITLE
Proxy settings not being used 

### ISSUE THREAD

**Issue by alex036** [Russell-Newton/TikTokPy#29]
Hi there,

I've added a `proxy={"server":"http" ...}` argument to the API but it's not actually sending the requests through the proxy.

Is there anything else I can do to test or ensure it's working through the proxy?

Thanks

**Comment by Russell-Newton** [comment]
It looks like I added the option to capture proxy settings, but I forgot to make sure they'd pass through to Playwright. Please try again with v0.1.11

**Comment by zakrian07** [comment]
how can i try with this please help needed

**Comment by Russell-Newton** [comment]
@zakrian07 please create a new issue with your bug/question so you can provide more details.
