### ISSUE TITLE
Without Watermark?

### ISSUE THREAD

**Issue by azickri** [Russell-Newton/TikTokPy#3]
Hey..
Its was great repository.

What is the response from get video and also the challenge without a watermark?

**Comment by Russell-Newton** [comment]
I'm not sure I follow. Are you asking for how to download a video without a watermark? As far as I know, the watermark that appears on the screen throughout the video cannot be removed, but the [instructions in the documentation](https://tiktokpy.readthedocs.io/en/latest/users/usage.html#download-videos-and-slideshows) for downloading a video will give you a video without the ending watermark/panel.

If you're looking for more information about the data returned by the library, it's laid out in the [API reference](https://tiktokpy.readthedocs.io/en/latest/generated/reference/tiktokapipy.api.TikTokAPI.html#tiktokapipy.api.TikTokAPI).

Can you clarify what you're looking for?

**Comment by azickri** [comment]
Sorry for the less questions.

I mean, can you add a TT video scraper without a watermark?

**Comment by Russell-Newton** [comment]
My library cannot download a video without the watermark that is placed over the video during the video. A link to such a version of the video is not provided directly from TikTok, so I'm not sure how this could be done without going to 3rd party resources like https://snaptik.app/en.

A solution that utilizes this specific 3rd party resource is linked in https://github.com/davidteather/TikTok-Api/issues/628.
If all you want is to download videos from TikTok without watermarks, I'd suggest you go directly to a tool like SnapTik or make use of something that pipes videos through SnapTik.

I will not be implementing anything into TikTokPy that removes the watermarks on videos. I think it's important to give credit to whomever created the video.

**Comment by azickri** [comment]
Okay.
Thanks for fast reply.
