### ISSUE TITLE
[QUESTION] how to use LightVideo

### ISSUE THREAD

**Issue by Tianqi-Dotes** [Russell-Newton/TikTokPy#31]
**Ask your question**
hi, 
please help to answer how to use LightVideo. In version 0.1.10, was using in this way 

'' lights = user.videos._light_models
        for v in lights:
            json = v.json()
"
when I replace `_light_models` with `LightVideo`, it is not working, how to use LightVideo?thanks

**Additional context**
Add any other context or screenshots about the question here.

**Comment by Russell-Newton** [comment]
models.video.LightVideo is the model that stores partial video data collected on a User page or Challenge page. The `_light_models` retrieved a list of these partial models.

What's changed from v0.1.10 is that these features are no longer hidden from documentation. `_light_models` has been renamed to `light_models` (remove the leasing underscore). Remove the underscore, and your code should work as it did previously.
