### ISSUE TITLE
Is there a way to download video without tiktok watermark?

### ISSUE THREAD

**Issue by s-alad** [Russell-Newton/TikTokPy#39]
Hey, I've followed all the setup on downloading videos in the [docs ](https://tiktokpy.readthedocs.io/en/latest/users/usage.html) and it all works great! However, I can't figure out how to download the regular videos without watermark.

 Slideshows only contain the raw images so those are completely fine, but after dumping the regular video content, I can't seem to find any address which does not contain the watermark. 

Any insight?

**Comment by Russell-Newton** [comment]
I am not aware of a way to do this directly. There are online tools that can do this for you, but it is not a planned feature for TikTokPy.
