### ISSUE TITLE
first run error

### ISSUE THREAD

**Issue by stolenvw** [Russell-Newton/TikTokPy#4]
got this error on first run
`async_api.py:157: RuntimeWarning: coroutine 'BrowserContext.clear_cookies' was never awaited`
2nd time it ran without error

**Comment by Russell-Newton** [comment]
Can you run `pip freeze` in your virtual environment so I can see what version of playwright you've got installed?

**Comment by stolenvw** [comment]
playwright==1.29.0

**Comment by Russell-Newton** [comment]
Fixed by #5. Playwright's documentation didn't indicate this as being a coroutine, but it looks like it is with the async version of Playwright's API.
