### ISSUE TITLE
[QUESTION] Is there a way get a random video using api.challenge?

### ISSUE THREAD

**Issue by jasonxubw** [Russell-Newton/TikTokPy#48]
**Ask your question**
I would like to randomly sample videos from a bunch of predefined challenges. Currently when running `api.challenge(challenge_name=hashtag, video_limit=1)`, it will always return the same video back.

E.g. with `challenge_name = 'fyp'`, I always get [this video](https://www.tiktok.com/@bellapoarch/video/6862153058223197445).

How does the API currently choose which videos to grab from a challenge?

**Comment by Russell-Newton** [comment]
I'm not sure how to do this. I can't seem to find a way to do this on TikTok's desktop website, so I don't have a way to emulate it. If you know of a way to do this on the website, then I could try to add this feature.

**Comment by Russell-Newton** [comment]
Closing this issue because there is no way to do this. TikTok's APIs always serve videos under a hashtag in an order determined by an algorithm.

Your best alternative would be to collect a large amount of videos with api.challenge and then pick a random one.
