### ISSUE TITLE
get data by username

### ISSUE THREAD

**Issue by ihabpalamino** [Russell-Newton/TikTokPy#53]
hello can i have an example of code to get by username number of likes shares comments of each video?

**Comment by Russell-Newton** [comment]
```py
from tiktokapipy.api import TikTokAPI

with TikTokAPI() as api:
    user = api.user(username)
    for video in user.videos:
        print(video.stats.digg_count, video.stats.share_count, video.stats.comment_count)
```

It's worth noting that these stats aren't 100% accurate all of the time, some times they're only accurate to a certain number of significant digits. Also if you're in the EU, this might not work without a VPN or proxy.

**Comment by ihabpalamino** [comment]
can i know please with video.stats what are things that i can get or scrap ?

**Comment by ihabpalamino** [comment]
i mean is it possible to get in data also the username the id of the post the date of the post..

**Comment by Russell-Newton** [comment]
I'd suggest taking a look at the documentation for the [Video model](https://tiktokpy.readthedocs.io/en/stable/generated/reference/tiktokapipy.models.video.Video.html#tiktokapipy.models.video.Video).

**Comment by ihabpalamino** [comment]
hello @Russell-Newton i have a question is it possible to do scraping either by choosing a period of dateo of videos and posts i wanna scrap or by number of posts?

**Comment by Russell-Newton** [comment]
Currently you can't grab from a date range, but you can limit the number of videos you get with something like:

`for video in user.videos.limit(20)`
