### ISSUE TITLE
Add tiktok url to the video object

### ISSUE THREAD

**Issue by reddere** [Russell-Newton/TikTokPy#54]
**Is your feature request related to a problem? Please describe.**
Since we are not able to download the videos from this library, at least I want to use it to fetch the tiktok url of a user profile and then use a website to download that tiktok link.

**Describe the solution you'd like**
For me, it would be useful to add some sort of "url" param to the user.videos.video

**Describe alternatives you've considered**
Tried requesting url from the play_addr, but as mentioned in other issues, it's not possible to get that url

**Comment by Russell-Newton** [comment]
At the moment, you can use the video_link function in the `tiktokapipy.models.video` package with `video.id` to get the video link.

```py
url = video_link(video.id)
```

**Comment by Russell-Newton** [comment]
This feature has been implemented in version 0.2.1. You can access the `video.url` property to retrieve the link to the TikTok page.

**Comment by reddere** [comment]
Thanks! Have you investigated about downloading the videos from the play_addr field, by the way?

**Comment by Russell-Newton** [comment]
I have not yet made any progress for this.
