### ISSUE TITLE
[QUESTION] Any way to keep track and resume from cursor?

### ISSUE THREAD

**Issue by TonyWilly** [Russell-Newton/TikTokPy#66]
**Ask your question**
I'd like to fetch all the videos from hashtags that have quite a few videos and possibly from sounds as well. I'm wondering if I can keep track of the current cursor or challenge object or api so that I can stop and resume from the same spot. Or maybe if I could supply a starting cursor to concurrently get the data from the same challenge faster? Thanks.

**Version Information**
Please include what versions of pydantic, playwright, and tiktokapipy you have installed (can be found with `pip freeze`).
pydantic==2.1.1
pydantic_core==2.4.0
playwright==1.36.0
tiktokapipy==0.2.2

**System Information**
Windows 10 64-bit Desktop

**Region Information**
Canada, using US proxies at the moment

**Additional context**
-

**Comment by Russell-Newton** [comment]
The `challenge.videos`, `user.videos`, and `video.comments` iterators all keep track of the current cursor internally. While it's a bit hacky, what you could do is something like this:

```py
challenge.videos._cursor = 30  # or whatever you want
for video in challenge.videos:
    ...
```

**Comment by TonyWilly** [comment]
I think this will work for me, thanks!
