### ISSUE TITLE
[FEATURE REQUEST] Is it possible to add the feature to get videos by limit page, here tiktok uses cursor next

### ISSUE THREAD

**Issue by truongbo17** [Russell-Newton/TikTokPy#68]
is it possible to add the feature to get videos by limit page, here tiktok uses cursor next

**Comment by Russell-Newton** [comment]
I'm unfamiliar with limit pages. Can you give an example API call or an example of where it comes up in regular use of TikTok?

**Comment by truongbo17** [comment]
`
$query = [
                "count"            => 30,
                "id"                  => $user_id,
                "cursor"           => $cursor,
                "type"              => 1,
                "secUid"          => $author_sec_id,
                "sourceType"  => 8,
                "appId"            => 1233
            ];
`

it is query

**Comment by Russell-Newton** [comment]
What's the endpoint? If I were to browse TikTok normally on desktop or mobile, where would this get called?

**Comment by truongbo17** [comment]
i used to go through these api and when it added limit , page . It will be much more useful if you randomize any number for cursor

check here: https://github.com/truongbo17/service-api/blob/main/app/app/Api/Nature/Tiktok/TiktokApi.php#L344
