### ISSUE TITLE
[QUESTION] What is video.video.download_addr?

### ISSUE THREAD

**Issue by eelegiap** [Russell-Newton/TikTokPy#71]
**Ask your question**
I am confused about how the code finds this aspect of a video. Is this `download_addr` something I could find in developer tools? I can't find in the repository where this object is assigned its value.

**Version Information**
playwright==1.37.0
pydantic==2.1.1
pydantic_core==2.4.0
tiktokapipy==0.2.3

Mac OS in a venv. / USA

**Comment by Russell-Newton** [comment]
The data is grabbed from TikTok's API, and pudantic is used to populate the objects and fields in the `tiktokapipy.models` package.

**Comment by eelegiap** [comment]
Gotcha, thanks for clarifying. I am still unclear on what part of the code ingests/parses the raw API data.
