### ISSUE TITLE
The videos aren't published because they are processing.

### ISSUE THREAD

**Issue by konax3** [Russell-Newton/TikTokPy#73]
Hi to all,
Since a week more or less the uploaded videos seems to be uploaded right but only can access them from my account. It seems like the video will be configured in private state or something like that but if i check the privacy configuation, is public. I've change to private and public again to force the change but nothing happens.

Another clue is if try to get the list of videos in my channel,  the videos of the last week doesn't appears. For example, i have 150 videos but if i retrive the list i only get 140, but if i go to my account the videos are there.

EDIT: Right now i've discovered if i try to share the video to get the URL, a messages appears saying "the video is processing". I have videos uploaded a week ago and still processing?? is a little bit weird, right?

Do you have any idea? 
I've runing the last version of the tiktokapipy  (0.2.3)

If you need more info, please no doubt to ask me.
Thanks in advance.

**Comment by Russell-Newton** [comment]
> ...if i try to share the video to get the URL, a messages appears saying "the video is processing".

You can't view the video normally on your browser either? I'm not sure what might be causing that.

Are you in the EU by any chance?

**Comment by konax3** [comment]
Yes! I'm on Spain. 
I don't know what is happening but i'm doing some test more and if i upload a video manually from my phone it happens the same. The video is being processed.
I think with this test we can say the script is working well, for any reason tiktok decides to stop publishing my videos. I've opened a ticket with tiktok support. 
I don't know what is happening, maybe they realised i'm uploading videos automatically. I don't know.
Thanks a lot and sorry for the incovenience.

**Comment by konax3** [comment]
Yes! I'm on Spain. 
I don't know what is happening but i'm doing some test more and if i upload a video manually from my phone it happens the same. The video is being processed.
I think with this test we can say the script is working well, for any reason tiktok decides to stop publishing my videos. I've opened a ticket with tiktok support. 
I don't know what is happening, maybe they realised i'm uploading videos automatically. I don't know.
Thanks a lot and sorry for the incovenience

**Comment by Russell-Newton** [comment]
It's also possible that the changes TikTok has put in place regarding user privacy/security in the EU involves restricting your videos for some reason. I'm not sure that that makes a whole lot of sense, but I know a lot of EU users have been affected by their changes in various ways.
